<?php

namespace Appacman\Model\Form;

use Core\Model\File;

class Image extends FormInput {

    /**
     * @var int $id. Image id
     */
    private $imageID = null;

    /**
     * @var string $image. Image Path
     */
    private $image = null;

    public function __construct($description, $id){
        parent::__construct($description, $id);

        $this->imageID = parent::getValue();
        $image = new File($this->imageID);
        $this->image = $image->getAbsolutePath();
    }

    public function getValue(){
        if( $this->image == null ){
            return '-';
        }else{
            return $this->getImage(); // TODO: Change the autogenerated stub
        }
    }

    public function getHTML(){
        if( $this->image == null ){
            return $this->inputType('file');
        }else{
            return '
                ' . $this->getImage() . '
                <a href="#" data-id="'. $this->imageID.'" data-name="'.$this->getFieldName().'" class="btn btn-danger btn-xs delete-image" title="'.gettext('Eliminar').'" data-toggle="confirmation">
                    <i class="fa fa-trash"></i>
                </a>
            ';
        }
    }

    private function getImage(){
        return '
            <a href="'.$this->image.'" class="pull-left media-object" target="_blank">
                <img src="'.$this->image.'" />
            </a>
        ';
    }

}