<?php

namespace Appacman\Model\Form;

use Core\Model\File;
use Core\Utils\Exception;

class Image extends FormInput {

    /**
     * @var int $id. Image id
     */
    private $imageID = null;

    /**
     * @var string $image. Image Path
     */
    private $image = null;

    public function __construct($description, $id, $table){
        parent::__construct($description, $id, $table);

        $this->loadImage(parent::getValue());
    }

    private function loadImage($imageID){
        $this->imageID = $imageID;
        $image = new File($this->imageID);
        $this->image = $image->getAbsolutePath();
    }

    public function getValue(){
        if( $this->image == null ){
            return '-';
        }else{
            return $this->getImage(); // TODO: Change the autogenerated stub
        }
    }

    public function getInputHTML($langID = null){
        if( $this->image == null ){
            return $this->inputType('file');
        }else{
            return '
                ' . $this->getImage() . '
                <a href="#" data-id="'. $this->imageID.'" data-name="'.$this->getFieldName().'" class="btn btn-danger btn-xs delete-image" title="'.gettext('Eliminar').'" data-toggle="confirmation">
                    <i class="fa fa-trash"></i>
                </a>
            ';
        }
    }

    public function canSave(){
        if( isset($_FILES[$this->getFieldName()]) && !empty($_FILES[$this->getFieldName()]['tmp_name']) ){
            return true;
        }
        return false;
    }

    private function getImage(){
        return '
            <a href="'.$this->image.'" class="pull-left media-object" target="_blank">
                <img src="'.$this->image.'" />
            </a>
        ';
    }

    public function getPostValue($langID = null){
        $image = new File();
        $imageID = $image->save( $_FILES[$this->getFieldName()] );

        if( $imageID === false ){
            throw new Exception('Unable to save image <pre>' . print_r($_FILES[$this->getFieldName()], true) . '</pre>');
        }
        $this->loadImage($imageID);
        return $imageID;
    }

}